version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
workflows:
  default:
    jobs:
    # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
    - aws-ecr/build-and-push-image:
        repo: nodejs-app
        tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
        dockerfile: Dockerfile
        path: .