apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app-staging
data:
  ENV_VALUE1: value1
  ENV_VALUE2: value2

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-staging-deployment
  labels:
    app: app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-staging
  template:
    metadata:
      labels:
        app: app-staging
    spec:
      containers:
        - name: app-staging
          image: 182620489580.dkr.ecr.us-west-1.amazonaws.com/nodejs-app:29
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config

---
kind: Service
apiVersion: v1
metadata:
  name: app-staging-service
spec:
  type: LoadBalancer
  selector:
    app: app-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
#${AWS_ECR_ACCOUNT_URL}/nodejs-app:${CIRCLE_BUILD_NUM}      